// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<Pending>", Scope = "namespace", Target = "~N:Warcraft")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification", Justification = "<Pending>")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.GameLogic.GoldMiningRoutine.TargetObject")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.HarvestLumberRoutine.TargetObject")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.GameLogic.MovementLogic.Routines")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.targetA")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.targetB")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.unit")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.targetA")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.targetB")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.Routine.unit")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.Model.Routine.PointToPointDistance(System.Drawing.Point,System.Drawing.Point)~System.Double")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.PathfindingLogic.FindPath(Warcraft.Model.Unit,Warcraft.Model.GameObject,System.Drawing.Point)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.GoldMiningRoutine.#ctor(Warcraft.Model.Unit,System.TimeSpan,Warcraft.Model.Building,Warcraft.Model.GoldMine,Warcraft.Model.GameModel,Warcraft.Model.OwnerEnum)")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.GameLogic.GoldMiningRoutine.TargetObject")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.GameLogic.GoldMiningRoutine.mining")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MovementLogic.PointToPointDistance(System.Drawing.Point,System.Drawing.Point)~System.Double")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MovementLogic.UpdateFacing(Warcraft.Model.Unit,System.Drawing.Point)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.PathfindingLogic.L1Distance(System.Drawing.Point,System.Drawing.Point)~System.Double")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.GameLogic.MovementLogic.Routines")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.UnitFactory.Create(System.String,System.Int32,System.Int32)~Warcraft.Model.Unit")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.UnitFactory.Create(System.String,System.Int32,System.Int32)~Warcraft.Model.Unit")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.AnimationLogic.SetAnimationString(Warcraft.Model.Unit)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.AnimationLogic.SetAnimationString(Warcraft.Model.Unit)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.AnimationLogic.ResetAnimationIndex(Warcraft.Model.Unit)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.AnimationLogic.IncrementAnimationIndex(Warcraft.Model.Unit)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.BuildingFactory.Create(System.String,System.Int32,System.Int32,System.Boolean)~Warcraft.Model.Building")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.BuildingFactory.Create(System.String,System.Int32,System.Int32,System.Boolean)~Warcraft.Model.Building")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.CoreLogic.InitNewBuilding(System.String,System.Drawing.Point)")]
[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison for clarity", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.CoreLogic.InitNewBuilding(System.String,System.Drawing.Point)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.Model.HarvestLumberRoutine.#ctor(Warcraft.Model.Unit,System.TimeSpan,Warcraft.Model.Building,Warcraft.Model.CombatObject,Warcraft.Model.GameModel,Warcraft.Model.OwnerEnum)")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.EnemyLogic.Step")]
[assembly: SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.HarvestLumberRoutine.TargetObject")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MineFactory.Create(System.String,System.Int32,System.Int32)~Warcraft.Model.GameObject")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MineFactory.Create(System.String,System.Int32,System.Int32)~Warcraft.Model.GameObject")]
[assembly: SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MineFactory.Create(System.String,System.Int32,System.Int32)~Warcraft.Model.GameObject")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.HUDBuilder.BuildHUD(Warcraft.Model.GameModel)~System.Collections.Generic.List{Warcraft.Model.Icon}")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.HUDBuilder.BuildHUD(Warcraft.Model.GameModel)~System.Collections.Generic.List{Warcraft.Model.Icon}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.CoreLogic.PositionInHitbox(System.Drawing.Point,System.Drawing.Rectangle)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "<Pending>", Scope = "member", Target = "~F:Warcraft.Model.HarvestLumberRoutine.mining")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MapBuilder.Build(Warcraft.Model.GameModel,System.Int32,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.CombatLogic.ResetUnit(Warcraft.Model.Unit)")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.CombatLogic.SetTarget")]
[assembly: SuppressMessage("Maintainability", "CA1508:Avoid dead conditional code", Justification = "<Pending>", Scope = "member", Target = "~M:Warcraft.GameLogic.MovementLogic.ValidateCollision(Warcraft.Model.GameObject,Warcraft.Model.Unit)~System.Boolean")]
